import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../components/header/Navbar'
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Alumni Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {/* <Navbar /> */}
      {children}

      </body>
    </html>
  );
}
